services:
  proxy:
    image: traefik:v3.2.1
    container_name: traefik
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # - ./traefik/acme.json:/acme.json:rw
    restart: always
    security_opt:
      - no-new-privileges:true

  db:
    build:
      context: .
      target: pb_prod
      dockerfile: Dockerfile
    container_name: pocketbase
    restart: always
    volumes:
      - ./pocketbase/pb_data:/pb/pb_data
      - ./pocketbase/pb_public:/pb/pb_public
      - ./pocketbase/pb_hooks:/pb/pb_hooks
      - ./pocketbase/pb_migrations:/pb/pb_migrations
    environment:
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pocketbase.rule=PathPrefix(`/api/`) || PathPrefix(`/_/`)"
      # - "traefik.http.routers.pocketbase.entrypoints=websecure"
      - "traefik.http.services.pocketbase.loadbalancer.server.port=8090"

  remix:
    build:
      context: .
      target: remix_prod
      dockerfile: Dockerfile
    container_name: remix
    restart: always
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.remix.rule=PathPrefix(`/`)"
      # - "traefik.http.routers.remix.entrypoints=websecure"
      - "traefik.http.services.remix.loadbalancer.server.port=3000"

networks:
  default:
    name: app_network
    driver: bridge
